[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
baseURL = 'https://gi4nlucac.github.io/portfolio/'
languageCode = 'en-us'
title = 'Gianluca Camarca'
theme = 'hello-friend-ng'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Gameplay Programmer & Technical Game Designer working professionally in the industry since 2021"

  disableReadOtherPosts = false

  # Enable sharing buttons
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Game developer portfolio"
  keywords = "game developer, portfolio"
  images = [""]

  # Custom CSS
  customCSS = ["/portfolio/css/custom.css"]

# Logo configuration
[params.logo]
  logoText = "Gianluca Camarca"
  logoMark = ">"
  logoCursorColor = "#FFFFFF"
  logoCursorAnimate = "2s"

[params.portrait]
  path     = ""
  alt      = "Profile picture"
  maxWidth = "150px"

# Main navigation buttons (Call to Action)
[menu]
  [[menu.main]]
    identifier = "resume"
    name       = "About me"
    url        = "resume/"
  [[menu.main]]
    identifier = "projects"
    name       = "My projects"
    url        = "projects/"

# Social links
[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/gianluca-camarca/"

[[params.social]]
  name = "github"
  url  = "https://gitlab.com/g.camarca"

[[params.social]]
  name = "email"
  url  = "#email-protected"

[params.footer]
  trademark = true
  rss = false
  copyright = true
  author = true

  topText = []
  bottomText = []
